### ISSUE TITLE
Broken import in LP phase processing function

### ISSUE THREAD

**Issue by krihabu** [meteoswiss-mdr/pyart#3]
Hi!

The function `phase_proc_lp_gf()` in pyart.correct is not executable because of inconsistency with the imports:

The file pyart/correct/phase_proc.py starts with
`from copy import deepcopy`
whereas in the ARM-DOE pyart master it is
`import copy`.

In `phase_proc_lp_gf()` the imported `deepcopy` is now once (in line 1820) called by `deepcopy(...)` but later (in lines 1837, 1842 and 1847) as `copy.deepcopy(...)`, which fails with `NameError: name 'copy' is not defined`.

Regards!

**Comment by meteoswiss-mdr** [comment]
Thanks for signaling @krihabu!

We will correct it in the source code in the coming days and in the next package release in some weeks. Please be patient and keep signaling any bug.

**Comment by meteoswiss-mdr** [comment]
Hi @krihabu,

I corrected this bug. If you install Py-ART from source it should work now. The next release of the package pyart_mch is going to take place in a month or so.

I close the issue for the moment but feel free to reopen it.
