### ISSUE TITLE
Bug in smoothing function

### ISSUE THREAD

**Issue by krihabu** [meteoswiss-mdr/pyart#4]
The function `smooth_masked_scan` in correct/phase_proc.py is not executable with argument `wind_type='mean'`, because the function `np.ma.mean()` does not except the keyword `overwrite_input`:

https://github.com/meteoswiss-mdr/pyart/blob/65666e7af723881a8d11c16ed734505a9c08765f/pyart/correct/phase_proc.py#L442-L444

**Comment by meteoswiss-mdr** [comment]
I corrected it by removing the offending keyword.

Closed for now
